server:
  port: 0

spring:
  application:
    name: dashboard-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.example.userservice.client: DEBUG

